version: '3'
services:
  db:
    build: ./mysql
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: <%= ENV['MYSQL_PASSWORD'] %>
  web:
    build: .
    volumes:
      - .:/myapp
      - public_data:/myapp/public
      - socket-data:/myapp/tmp/sockets
    tty: true
    stdin_open: true
    depends_on:
      - db
  server:
    build: ./nginx
    volumes:
      - socket-data:/myapp/tmp/sockets
      - public_data:/myapp/public
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public_data:
  socket-data:
  db-volume: