version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb -E production"
    volumes:
      - .:/myapp
      - bundle_path:/bundle
      - public-data:/myapp/public
      - socket-data:/myapp/tmp/sockets
      - log-data:/myapp/log
    ports:
      - 3000:3000
    environment:
      - BUNDLE_PATH=/bundle
    tty: true
    stdin_open: true
  server:
    build: ./nginx
    volumes:
      - socket-data:/myapp/tmp/sockets
      - public-data:/myapp/public
    ports:
      - 80:80
    depends_on:
      - web
    
    
volumes:
  bundle_path:
  public-data:
  socket-data:
  log-data:
  db-volume: