version: 2
jobs:
  build:
    docker:
    machine:
      image: circleci/classic:edge
    working_directory: ~/myapp
    steps:
      - checkout
      - run:
          name: addenv
          command:  |
            echo GURUNAVI_API_KEY=$GURUNAVI_API_KEY > .env
            echo SECRET_KEY_BASE=$SECRET_KEY_BASE >> .env
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
      
  deploy:
   machine:
    image: circleci/classic:edge
   working_directory: ~/myapp
   steps:
    - checkout
    - run:
       name: into ecs
       command: $(aws ecr get-login --region ${AWS_REGION} --no-include-email)
    - run:
       name: ECR build
       command: docker build -t ${AWS_ID}/gnavi_web .
    - run:
        name: ECR push
        command: docker push ${AWS_ID}/gnavi_web
    - run:
       name: deploy
       command: scripts/ecs-deploy --cluster lll --service-name gnavi-sv --region ${AWS_REGION} --image ${AWS_ID}/gnavi_web:latest --timeout 200
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build