version: 2
jobs:
  build:
    docker:
        - image: circleci/ruby:2.6.3
            environment:
                RAILS_ENV: test
                MYSQL_HOST: 127.0.0.1

        - image: circleci/mysql:5.7
            environment:
                MYSQL_USER: root
                MYSQL_DB: app_test
                MYSQ_PASSWORD: password
                ports:
                    - "3306:3306"

    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create
      - run:
          name: "db migrate"
          command: docker-compose run web rails db:migrate
      - run:
          name: test
          command: docker-compose run web bundle exec rspec #RSpecを使う場合は、bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down