version: 2
jobs:
  build:
    docker:
    machine:
      image: circleci/classic:edge
    working_directory: ~/rest-web
    steps:
      - checkout
      - run:
           name: up
           command: docker-compose up -d
      - run:
          name: sleep for DB launch
          command: |
            sleep 10
      - run:
           name: bundle install
           command: |
            docker-compose run web bundle install
      - run:
          name: migrate db
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: test
          command: |
            docker-compose run web bundle exec  rspec ./spec/models/
  deploy:
   machine:
    image: circleci/classic:edge
   environment:
    AWS_ID: 231421272561.dkr.ecr.ap-northeast-1.amazonaws.com
   steps:
    - checkout
    - run:
       name: into ecs
       command: 
    - run:
       name: ECR build
       command: docker build -t ${AWS_ID}/gnavi_web .
    - run:
        name: ECR push
        command: docker push ${AWS_ID}/gnavi_web
    - run:
       name: deploy
       command: scripts/ecs-deploy --cluster gnavi --service-name gnavi --image 231421272561.dkr.ecr.ap-northeast-1.amazonaws.com/gnavi_web:latest --timeout 600
    
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
          