version: 2
jobs:
  build:
    docker:
    machine:
      image: circleci/classic:edge

    working_directory: ~/rest-web

    steps:
      - checkout

      - run:
          name: image build
          command: |
            docker-compose up -d

      - run:
          name: docker-compose ps
          command: |
            docker-compose ps
      - run:
          name: sleep for DB launch
          command: |
            sleep 10

      - run:
          name: migrate db
          command: docker-compose run web rails db:create db:migrate

      - run:
          name: test
          command: |
            docker-compose exec web bundle exec  rspec ./spec/models/
