version: 2
jobs:
  build:
    docker:
    machine:
      image: circleci/classic:edge
    working_directory: ~/myapp
    steps:
      - checkout
      - run:
           name: add env
           command: echo MYSQL_USER=$MYSQL_USER > .env && echo MYSQL_USER=$MYSQL_PASSWORD >> .env && echo GURUNAVI_API_KEY=$GURUNAVI_API_KEY >> .env
      - run:
           name: up
           command: docker-compose up -d

  deploy:
   machine:
    image: circleci/classic:edge
   steps:
    - checkout
    - run:
       name: into ecs
       command: $(aws ecr get-login --region ${AWS_REGION} --no-include-email)
    - run:
       name: ECR build
       command: docker build -t ${AWS_ID}/gnavi_web .
    - run:
        name: ECR push
        command: docker push ${AWS_ID}/gnavi_web
    - run:
        name: migration
        command: aws ecs run-task --region ap-northeast-1 --cluster gnavi --task-definition volume --overrides file://run_task_db_migrate.json

    - run:
       name: deploy
       command: scripts/ecs-deploy --cluster gnavi --service-name gnavi2 --region ${AWS_REGION} --image ${AWS_ID}/gnavi_web:latest --timeout 600
    
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build